# Generated by Django 4.2.2 on 2023-06-30 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 10, 10, 56, 990322)),
        ),
    ]
